Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

#Answer

There is a difference in the data types of the list_ and array_list variables.

The list_ variable is a Python list containing string elements: ['1', '2', '3', '4', '5']. The data type of the elements in the list is string.

On the other hand, the array_list variable is a NumPy array created from the list_ using the np.array() function. By default, the np.array() function infers the data type of the array based on the data type of the input elements. In this case, since the elements in the list_ are strings, the data type of the resulting array will be a string as well.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


                      -------------------------------------------------------------------

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
#Answer

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in the list
for element in list_:
    print(type(element))

# Print data types of elements in the array
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


                      -------------------------------------------------------------------

Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [3]:
#Answer

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)


In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in the list
for element in list_:
    print(type(element))

# Print data types of elements in the array
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


                      -------------------------------------------------------------------

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [5]:
#Answer

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of the array
shape = num_array.shape

# Find the size of the array
size = num_array.size

print("Shape:", shape)
print("Size:", size)


Shape: (2, 3)
Size: 6


                      -------------------------------------------------------------------

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [6]:
#Answer

import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


                       -------------------------------------------------------------------

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [7]:
#Answer

import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


                        -------------------------------------------------------------------